name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        dotnet: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: |
          pnpm build

      - name: Build storybook
        run: pnpm build-storybook

      - name: Lint
        run: |
          pnpm lint

      - name: Test
        run: |
          pnpm test

  e2e-linux:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]
        dotnet: [ '6.0.x' ]
    
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build storybook
        run: |
          pnpm build-storybook

      - name: e2e
        run: |
          pnpm e2e

  e2e-macos:
    
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]
        dotnet: [ '6.0.x' ]
    
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build storybook
        run: |
          pnpm build-storybook

      - name: e2e
        run: |
          pnpm e2e

  e2e-win:
    
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]
        dotnet: [ '6.0.x' ]
    
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: |
          pnpm install

      - name: Build storybook
        run: |
          pnpm build-storybook

      - name: e2e
        run: |
          pnpm e2e
